# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoviesChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  pod 'Alamofire', '~> 5.0'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Kingfisher', '~> 5.0'

  # Pods for MoviesChallenge

end
