# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyMovies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyMovies
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'FSPagerView'
  pod 'lottie-ios', '~> 2.5.3'
  pod 'YouTubePlayerSwift'

  target 'MyMoviesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyMoviesUITests' do
    # Pods for testing
  end

end
