# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOS_Challenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire', '~> 5.0'
	pod "YoutubePlayer-in-WKWebView", "~> 0.3.0"

  # Pods for IOS_Challenge

  target 'IOS_ChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOS_ChallengeUITests' do
    # Pods for testing
  end

end
