# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieDB_AIS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieDB_AIS
  pod 'Moya'
  pod 'Kingfisher'

  target 'MovieDB_AISTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieDB_AISUITests' do
    # Pods for testing
  end

end
